baseURL = 'https://rmitlibrary.github.io/dewey-design/'
languageCode = 'en-au'
title = 'Dewey design system'

[params]
name = 'Simba'

[markup.goldmark.renderer]
unsafe = true

[menu]
    [[menu.main]]
        name = "Introduction"
        url = "/introduction/"
        weight = 100
    [[menu.main]]
        name = "Getting started"
        parent = "Introduction"
        url = "/"
        weight = 102
    [[menu.main]]
        name = "Accessibility"
        parent = "Introduction"
        url = "/introduction/accessibility/"
        weight = 103
    [[menu.main]]
        name = "Help"
        parent = "Introduction"
        url = "/introduction/help/"
        weight = 104   
    [[menu.main]]
        name = "Anatomy of a page"
        url = "/introduction/anatomy/"
        parent = "Introduction"
        weight = 105
    [[menu.main]]
        name = "Headings"
        url = "/introduction/headings/"
        parent = "Introduction"
        weight = 106
    [[menu.main]]
        name = "Visual language"
        url = "/visual/"
        weight = 200 
    [[menu.main]]
        name = "Breakpoints and columns"
        url = "/visual/breakpoints/"
        parent = "Visual language"
        weight = 206
    [[menu.main]]
        name = "Colour"
        url = "/visual/colour/"
        parent = "Visual language"
        weight = 207
    [[menu.main]]
        name = "Icons"
        url = "/visual/icons/"
        parent = "Visual language"
        weight = 208
	[[menu.main]]
        name = "Links"
        url = "/visual/links/"
        parent = "Visual language"
        weight = 209
    [[menu.main]]
        name = "Spacing"
        url = "/visual/spacing/"
        parent = "Visual language"
        weight = 210
    [[menu.main]]
        name = "Typography"
        url = "/visual/typography/"
        parent = "Visual language"
        weight = 211
        
    [[menu.main]]
        name = "Simple components"
        url = "/components-simple/"
        weight = 300
    [[menu.main]]
        name = "Accordions"
        url = "/components-simple/accordions/"
        parent = "Simple components"
        weight = 312
    [[menu.main]]
        name = "Blockquotes"
        url = "/components-simple/blockquotes/"
        parent = "Simple components"
        weight = 313
    [[menu.main]]
        name = "Buttons"
        url = "/components-simple/buttons/"
        parent = "Simple components"
        weight = 314
	[[menu.main]]
        name = "Tables"
        url = "/components-simple/tables/"
        parent = "Simple components"
        weight = 315
    
    [[menu.main]]
        name = "Footer"
        url = "/components-complex/footer/"
        parent = "Complex components"
        weight = 413
    [[menu.main]]
        name = "Images"
        url = "/components-complex/images/"
        parent = "Complex components"
        weight = 414
    [[menu.main]]
        name = "Navigation"
        url = "/components-complex/navigation/"
        parent = "Complex components"
        weight = 415
	[[menu.main]]
        name = "Top navigation"
        url = "/components-complex/top-nav/"
        parent = "Complex components"
        weight = 417
	[[menu.main]]
        name = "Video"
        url = "/components-complex/video/"
        parent = "Complex components"
        weight = 417
    [[menu.main]]
        name = "Example 1"
        url = "/examples/example-1/"
        parent = "Examples"
        weight = 502
    [[menu.main]]
        name = "Example 2"
        url = "/examples/example-2/"
        parent = "Examples"
        weight = 503
	[[menu.main]]
        name = "Example 3"
        url = "/examples/example-3/"
        parent = "Examples"
        weight = 504
    